# Generated by Django 3.0.8 on 2020-07-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okashi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='choice1',
        ),
        migrations.AddField(
            model_name='post',
            name='question1_0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='question1_1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_choice1',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
